### ISSUE TITLE
[Bug] When playing offline music, displayed song progress will jump ahead on CarPlay UI if music is stopped and resumed.  Phone remains accurate.

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#162]
## Brief description of the issue:
While testing offline caches on CarPlay, I noticed something odd: if you start playing an offline block, then pause for a bit, the playback progress of the song shown on CarPlay UI has jumped ahead, while the playback progress on the phone remains accurate.  The audio does not skip ahead; therefore, this is a UI glitch only affecting CarPlay.

### Steps to reproduce:
1. Prepare an offline block of music (either before or while connected to CarPlay).
2. Connect to CarPlay.
3. Start playing the offline block of music.
4. After a few seconds, pause the music.
5. Wait any amount of time, but ideally at least 1 minute to observe a noticeable jump.
6. Unpause music. 
7. Check the playback progress on the phone vs. the CarPlay UI.

I think that CarPlay's progress per song is being calculated **based on the time of day** it started playing that track, not the actual song length or current position.  

### Expected result:
Song playback bar would show the same time on phone and CarPlay UI.

### Actual result:
CarPlay's progress will be much farther ahead than the phone, and will not be accurate relative to the current song.

NOTE: this only happens with OFFLINE blocks.  Online streaming is not affected; the playback progress bars match perfectly after repeated attempts of steps of 4-8 above.

### Where did you see it? (App build version, device type and iOS version):
Build 62, iPhone 12 Pro, iOS 16.4.1, Kia Niro 2017.

*(Where possible, please attach Please provide screenshots or error message text)*

Screen shots in the next comment.

**Comment by bradtchapman** [comment]
The following set of screenshots illustrates the progress of a song relative to how much real time had elapsed.  

The device was unplugged and reconnected several times, and the screenshots were taken immediately after playback resumed and the progress bar had updated.

From 6:20 - 6:26, the song had only played back about 30 real seconds, but CarPlay showed an elapsed time of more than 5 minutes, which corresponds to the actual real-world time that had passed.


![01-app](https://github.com/BillGoldsmith/iOS-bugfest/assets/32527656/9a691763-4047-4abb-a416-f7cbd2d57876)
![01-car](https://github.com/BillGoldsmith/iOS-bugfest/assets/32527656/34a00f2d-6d83-4e62-b38b-7057dcb8fa93)
![02-app](https://github.com/BillGoldsmith/iOS-bugfest/assets/32527656/d7510ad5-742f-42dc-bfc2-ca4800651126)
![02-car](https://github.com/BillGoldsmith/iOS-bugfest/assets/32527656/106b0217-7678-4ad7-9450-9bc88b9f8490)
![03-app](https://github.com/BillGoldsmith/iOS-bugfest/assets/32527656/10f67ee6-9cc2-4b52-b65f-18edb2ddfb4e)
![03-car](https://github.com/BillGoldsmith/iOS-bugfest/assets/32527656/177eb6b3-5a33-46fa-b084-93e520833ea7)
![04-app](https://github.com/BillGoldsmith/iOS-bugfest/assets/32527656/6f179350-a34a-4ebd-bb16-c5b418d0a205)
![04-car](https://github.com/BillGoldsmith/iOS-bugfest/assets/32527656/9aaed803-4273-472b-976a-b8a3e198700a)
![05-app](https://github.com/BillGoldsmith/iOS-bugfest/assets/32527656/8eab1ef5-c2cb-4e38-95be-7f4ebc44cf0f)
![05-car](https://github.com/BillGoldsmith/iOS-bugfest/assets/32527656/227638a5-a9fe-429e-bc63-d157588db9f2)

**Comment by bradtchapman** [comment]
@donshefer : I was able to reproduce this without disconnecting the phone.  Just pausing was enough.

**Comment by RPNate1** [comment]
How is this now? Carpay broke and was fixed...

**Comment by bradtchapman** [comment]
I still see the time discrepancies on Bluetooth connections in multiple vehicles.  

Not unique to CarPlay, apparently.  It's displaying whatever elapsed song time the app says it is.  

There seems to be a running timer elsewhere in the code that tracks the **elapsed real time** since the song started playing, even if the song is paused.  That elapsed real time is displayed briefly before being overridden by the **song's elapsed time**.

**Comment by RPNate1** [comment]
This is an interesting one...

**Comment by bradtchapman** [comment]
Yes, @RPNate1, and an issue I've reported numerous times before :-)

**Comment by RPNate1** [comment]
checking on this one...anyone? Bueller??

**Comment by donshefer** [comment]
Fixed in build 80

**Comment by RPNate1** [comment]
@bradtchapman you're up, check this one as well? OMG 3 bugs left!!

**Comment by RPNate1** [comment]
@bradtchapman I talked with Don about this today and he found what was causing this. Check it out.

**Comment by bradtchapman** [comment]
@RPNate1 : in Build 81, or a future build?  I haven't had a chance to test build 81 in the CarPlay-equipped vehicle, but I think this was affecting playback in any scenario, not just CarPlay.

**Comment by RPNate1** [comment]
b81, I believe...

**Comment by RPNate1** [comment]
please give this a check @bradtchapman I want to get this off the list ASAP

**Comment by bradtchapman** [comment]
No, it's still happening in build 82.  The "Now Playing" timers, as well as any values received by the Bluetooth car stereo, are incorrect.  If music is paused for the first time, the displayed progress is 0:02, no matter where the song is.  When resuming, the time jumps around a bit before settling down.  If paused later, the progress shows the last played time.  When resumed, it jumps ahead briefly before reverting to the actual elapsed time.

The only progress meter that's been accurate this whole time, no matter how much I try to abuse the playback controls via other means, is the progress bar inside the RP app at the bottom of the screen.  

How is the app's own progress bar computing the elapsed time?  Why can't *that* time be passed to the rest of the system? Genuinely curious here, since this doesn't appear to be a super hard problem on its face.

**Comment by donshefer** [comment]
" If music is paused for the first time, the displayed progress is 0:02, no matter where the song is. "
@bradtchapman I am not seeing this. Can you please give me more detail?

As for the jumping around, the system attempts to keep its own count, but it does get confused. We are constantly updating the system with the correct value. That is why it seems to go off, then correct itself. Because we are sending the correct value about once every second.
As far as I can tell, this seems to be working as expected.

**Comment by RPNate1** [comment]
Is that a satisfactory answer to the perceived bug, @bradtchapman ?
