### ISSUE TITLE
[Bug] Some content is cut off on the left and right of the iPad in landscape mode

### ISSUE THREAD

**Issue by ChristianNoc** [BillGoldsmith/iOS-bugfest#188]
## Brief description of the issue:
See screenshots, maybe a general problem. Maybe already addressed in #172 but not only elements the whole content is also cut off.
Anyway: Cool summery about all channels…

![IMG_0143](https://github.com/BillGoldsmith/iOS-bugfest/assets/134198993/5b48e8e6-2f5e-459b-afc1-df1a900b40c1)

![IMG_0144](https://github.com/BillGoldsmith/iOS-bugfest/assets/134198993/872f1aa0-30e1-4382-82d2-b8c781a43119)

### Where did you see it? (App build version, device type and iOS version):
Build 0.9 (65), iPad mini 5, iOS iPadOS 16.5 

*(Where possible, please attach Please provide screenshots or error message text)*

**Comment by RPNate1** [comment]
fixed b71

**Comment by ChristianNoc** [comment]
@RPNate1 @donshefer 

NOT fully fixed pls reopen.
Build 0.9 (72), iPad mini 5, iOS iPadOS 16.5 

In the start screen it’s ok, after start playing problem still there with control buttons on the right and in other views on the top left and right… so play control still isn’t possible in landscape mode…

![IMG_0181](https://github.com/BillGoldsmith/iOS-bugfest/assets/134198993/e5516ed7-28fa-4e3b-96bd-688743d2b08c)

![IMG_0182](https://github.com/BillGoldsmith/iOS-bugfest/assets/134198993/d15e96e7-3171-478f-ba87-33ef98e237cd)

![IMG_0183](https://github.com/BillGoldsmith/iOS-bugfest/assets/134198993/0c589ca7-73a9-497d-b97f-0f906f03b51c)

**Comment by RPNate1** [comment]
grrrr. reopening. I'm getting ready to scrap landscape.

**Comment by ChristianNoc** [comment]
@RPNate1 please not (scraping). When u want to use an iPad or iPad mini as playing device you will use it in landscape mode only because of the Installation possibilities with appropriate sleeves in landscape mode. This is the perfect use case for an old iPad as RP music player with external DAC. Only portrait mode for an iPad that would be useless. Especially the info screens are very helpful in landscape mode.

I promise to test the landscape mode immediately with a new version and will close that issue for you when fixed. I hope that soothes a little ;-).

**Comment by RPNate1** [comment]
Sorry, I vented a bit. We'll keep plugging away and get it sorted @ChristianNoc

**Comment by ChristianNoc** [comment]
@RPNate1  absolutely understandable. I remembered a e-commerce web project where I had that testing lead, that responsible screen design is horrible, you have to test almost ever screen size. And I am not really patient. Really terrible. Sometimes I think that this IT stuff gets more and more complicated and expensive of course…

**Comment by donshefer** [comment]
Please check out build 74, should be better now.

**Comment by ChristianNoc** [comment]
@donshefer 

mh just a Little better:

simple  view (no Burger menue on the bottom right)

![IMG_0204](https://github.com/BillGoldsmith/iOS-bugfest/assets/134198993/3c475c8b-6e53-4da1-9b40-11659eff0c01)

Open info screen:
Burger menue appears, but something in the top goes wrong… and on the bottom left…

![IMG_0205](https://github.com/BillGoldsmith/iOS-bugfest/assets/134198993/8db1ead9-f977-48a4-81ef-9189df73a863)

when I am testing it my memories from my web project comes to my mind. Every screen size acts different…horrible… are you working here with css sheets, it’s a webview, isn’t it?

![IMG_0206](https://github.com/BillGoldsmith/iOS-bugfest/assets/134198993/fc7a7f4f-e153-4572-9030-2c9ba7891e98)

Build 0.9 (74), iPad mini 5, iOS iPadOS 16.5

**Comment by RPNate1** [comment]
Fixed on the iPad Air. 16.4.1.
I'll check my iPad 8 this afternoon.

**Comment by RPNate1** [comment]
@ChristianNoc ?

**Comment by ChristianNoc** [comment]
@RPNate1 

still not fixed with 74 as commented yesterday…
https://github.com/BillGoldsmith/iOS-bugfest/issues/188#issuecomment-1588112543

on all of my 3 screenshots there are some problems… a lil better but not fixed…

**Comment by donshefer** [comment]
I'm still not entirely happy with it, but at least now everything is shown.
Updated in build 76.

**Comment by RPNate1** [comment]
formatting will get more passes before public release. for now fixed in b76
